package com.project.hotel.enums;

public enum NotificationType {
    HOTEL_STATUS,
    MANUAL_ADMIN,
    NEW_BOOKING,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_CHECKIN,
    BOOKING_CHECKOUT,
    PAYMENT_SUCCESS,
    SYSTEM,
    BOOKING_REMINDER,
    BOOKING_EXPIRED
}
